version: '3'
networks:
  festival-shop.net:
    driver: bridge
services:

  # service api.festival-shop : api pour la prise de commandes
  #
  api.festival-shop:
    image: 'canals/php:latest'
    env_file: ./shop.env
    ports:
      - '11110:443'
    volumes:
      - ../shop.festival/public:/var/www/html
      - ../shop.festival:/var/www
    working_dir: /var/www/
    networks:
      festival-shop.net:
        aliases:
          - api.festival-shop.local
    depends_on:
      - festival-shop.db



  # service sql pour le stockage des commandes -
  # utilisé par l'api order
  festival-shop.db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: ./shop.env
    ports:
      - '11111:3306'
    networks:
      - festival-shop.net
    volumes:
      - ../shop.festival/sql:/var/sql

  # service administration des bases sql
  #
  adminer:
    image: adminer
    env_file: ./shop.env
    command: php -S 0.0.0.0:8080 -t /var/www/html
    ports:
      - '11112:8080'
    networks:
      - festival-shop.net


  api.festival-auth:
    image: 'canals/php:latest'
    env_file: ./auth.env
    ports:
      - '11113:443'
    volumes:
      - ../auth.festival/public:/var/www/html
      - ../auth.festival:/var/www
    working_dir: /var/www
    networks:
      festival-shop.net:
        aliases:
          - auth.festival.local
    depends_on:
      - festival-auth.db

  festival-auth.db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: ./auth.env
    ports:
      - '11114:3306'
    networks:
      - festival-shop.net
    volumes:
      - ../auth.festival/sql:/var/sql